In [1]:
import mediapipe as mp
import cv2
import time
import numpy as np
import pandas as pd
import os


Bad key text.latex.preview in file D:\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 123 ('text.latex.preview : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key mathtext.fallback_to_cm in file D:\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.jpeg_quality in file D:\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')
You probably need to get an updated matplotli

In [2]:
mpPose = mp.solutions.pose
pose = mpPose.Pose()
mpDraw = mp.solutions.drawing_utils # For drawing keypoints
points = mpPose.PoseLandmark # Landmarks
path = "H:/basketball_data/train/dribbling" # enter dataset path
data = []
for p in points:
    x = str(p)[13:]
    data.append(x + "_x")
    data.append(x + "_y")
    data.append(x + "_z")
    data.append(x + "_vis")
data = pd.DataFrame(columns = data)

In [3]:
count = 0
temp = []
for img in os.listdir(path):
        try:
            temp = []
            img = cv2.imread(path + "/" + img)
            imageWidth, imageHeight = img.shape[:2]
            imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            blackie = np.zeros(img.shape) # Blank image
            results = pose.process(imgRGB)
            if results.pose_landmarks:
                    # mpDraw.draw_landmarks(img, results.pose_landmarks, mpPose.POSE_CONNECTIONS) #draw landmarks on image
                    mpDraw.draw_landmarks(blackie, results.pose_landmarks, mpPose.POSE_CONNECTIONS) # draw landmarks on blackie
                    landmarks = results.pose_landmarks.landmark
                    for i,j in zip(points,landmarks):
                            temp = temp + [j.x, j.y, j.z, j.visibility]
                    data.loc[count] = temp
                    count +=1
            cv2.imshow("Image", img)
            cv2.imshow("blackie",blackie)
            cv2.waitKey(100)
        except AttributeError:
            continue
 
data.to_csv("H:\\basketball_data\\generate_csv\\dribbling_dataset.csv") # save the data as a csv file

KeyboardInterrupt: 

In [4]:
df_shooting = pd.read_csv('H:\\basketball_data\\generate_csv\\shooting_dataset.csv')
df_dribbling = pd.read_csv('H:\\basketball_data\\generate_csv\\dribbling_dataset.csv')
df_not_shooting= pd.read_csv('H:\\basketball_data\\generate_csv\\not_shooting_dataset.csv')

In [5]:
df_shooting['target']=1 #1代表投篮
df_not_shooting['target']=0 #0代表不投篮
df_dribbling['target']=2#2代表运球

In [6]:
df=df_shooting.append(df_not_shooting)

In [7]:
df=df.append(df_dribbling)

In [8]:
df.reset_index(drop=True, inplace=True)
df=df.iloc[:,1:]

In [9]:
df

NOSE_x    NOSE_y    NOSE_z  NOSE_vis  LEFT_EYE_INNER_x  \
0    0.447995  0.422057 -0.192104  0.976368          0.428352   
1    0.444185  0.418227 -0.119033  0.978704          0.420231   
2    0.598761  0.584198 -0.220648  0.980785          0.609114   
3    0.654963  0.585802 -0.159049  0.982583          0.660644   
4    0.636699  0.630864 -1.015364  0.979376          0.639814   
..        ...       ...       ...       ...               ...   
367  0.388577  0.162807 -0.506226  0.974281          0.392410   
368  0.317420  0.335500 -0.082653  0.974477          0.318722   
369  0.368994  0.161423 -0.434519  0.977003          0.365324   
370  0.589108  0.210318 -0.113248  0.973732          0.604631   
371  0.511491  0.238113 -0.445974  0.975761          0.511345   

     LEFT_EYE_INNER_y  LEFT_EYE_INNER_z  LEFT_EYE_INNER_vis  LEFT_EYE_x  \
0            0.403105         -0.189175            0.975644    0.424037   
1            0.401712         -0.131995            0.978045    0.415011   
2            0.568965         -0.268376            0.980209    0.610842   
3            0.578566         -0.175945            0.982128    0.662748   
4            0.636273         -1.043486            0.980421    0.640712   
..                ...               ...                 ...         ...   
367          0.149425         -0.494388            0.974569    0.393392   
368          0.323603         -0.079514            0.975736    0.318108   
369          0.147152         -0.413374            0.978139    0.370466   
370          0.234858         -0.106233            0.975471    0.605076   
371          0.213875         -0.427038            0.977371    0.508637   

     LEFT_EYE_y  ...  RIGHT_HEEL_vis  LEFT_FOOT_INDEX_x  LEFT_FOOT_INDEX_y  \
0      0.403354  ...        0.463257           0.233054           0.656314   
1      0.402075  ...        0.457355           0.431522           0.302145   
2      0.568814  ...        0.489109           0.607878           0.708306   
3      0.579440  ...        0.512048           0.633153           0.896688   
4      0.637543  ...        0.464135           0.554988           0.533542   
..          ...  ...             ...                ...                ...   
367    0.148398  ...        0.622347           0.453690           0.591541   
368    0.321979  ...        0.644249           0.213280           0.653540   
369    0.149579  ...        0.627812           0.706509           1.494591   
370    0.218196  ...        0.612483           0.388899           0.689952   
371    0.208078  ...        0.607586           0.518212           0.915480   

     LEFT_FOOT_INDEX_z  LEFT_FOOT_INDEX_vis  RIGHT_FOOT_INDEX_x  \
0             1.443197             0.461520            0.373873   
1             0.868637             0.440689            0.476036   
2             0.384028             0.412519            0.715843   
3             0.282045             0.468217            0.650054   
4             0.955860             0.430439            0.565777   
..                 ...                  ...                 ...   
367          -0.010825             0.632335            0.360733   
368          -0.009635             0.640510            0.217217   
369          -0.502739             0.634686            0.565758   
370           0.234768             0.596911            0.335951   
371           1.093337             0.586932            0.613716   

     RIGHT_FOOT_INDEX_y  RIGHT_FOOT_INDEX_z  RIGHT_FOOT_INDEX_vis  target  
0              0.543332            1.101894              0.504405       1  
1              0.283403            0.392622              0.515855       1  
2              1.047531            0.468511              0.534481       1  
3              0.900786            0.541243              0.562339       1  
4              0.575271            1.080059              0.509488       1  
..                  ...                 ...                   ...     ...  
367            0.683429           -0.183054        

## SVC分类器

In [13]:
from sklearn.svm import SVC
data = df
temp=[]
X,Y = data.iloc[:,:132],data['target']
model = SVC(kernel = 'poly')#rbf kernel
model.fit(X,Y)
mpPose = mp.solutions.pose
pose = mpPose.Pose()
mpDraw = mp.solutions.drawing_utils
path1 = "H:\\basketball_data\\test\\test.jpg"
img = cv2.imread(path1)
imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
results = pose.process(imgRGB)
if results.pose_landmarks:
        landmarks = results.pose_landmarks.landmark
        for j in landmarks:
                temp = temp + [j.x, j.y, j.z, j.visibility]
        y = model.predict([temp])
        if y == 0:
            asan = "not shooting"
        if y == 2:
            asan = 'dribbling'
        else:
            asan = "shooting"
        print(asan)
        cv2.putText(img, asan, (50,50), cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,0),3)
        cv2.imshow("image",img)
        cv2.waitKey()
        cv2.destroyAllWindows()

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=10)

In [30]:
predictions = model.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[14  8 14]
 [ 2 34  1]
 [ 1  0 19]]
0.7204301075268817


## 参数优化

### rbf  C值

In [56]:
model = SVC(kernel = 'rbf')#rbf kernel
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [57]:
predictions = model.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[14  6 16]
 [ 3 31  3]
 [ 3  0 17]]
0.6666666666666666


C值

In [58]:
model = SVC(kernel = 'rbf', C=10)#rbf kernel
model.fit(X_train,y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [59]:
predictions = model.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[18  6 12]
 [ 5 32  0]
 [ 3  0 17]]
0.7204301075268817


是否出现了过拟合现象

In [63]:
model1 = SVC(kernel = 'rbf', C=100)#rbf kernel
model1.fit(X_train,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [64]:
predictions = model1.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[27  5  4]
 [ 3 32  2]
 [ 3  0 17]]
0.8172043010752689


### 一个新的训练集和测试集

In [65]:
model2 = SVC(kernel = 'rbf', C=1000)#rbf kernel
model2.fit(X_train,y_train)

SVC(C=1000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [66]:
predictions = model2.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[29  4  3]
 [ 4 31  2]
 [ 4  0 16]]
0.8172043010752689
